### ISSUE TITLE
need permissions？

### ISSUE THREAD

**Issue by DuanDuanPan** [SkrewEverything/Command-Cache#1]
environment:OSX 10.14.2 ,iTerm2 Build 3.0.12
Command-Cache:1.0.1

can not cache command,Recently Used is empty.
<img width="500" alt="wx20190126-111518 2x" src="https://user-images.githubusercontent.com/4475078/51781980-c1486b00-215b-11e9-953a-084e9ea8aeab.png">

**Comment by SkrewEverything** [comment]
@DuanDuanPan 

I have only written this for default Terminal for macOS and Linux.

So, I haven't tested it with iTerm2(thinking to do it though in future).

The default Terminal loads `.bashrc` present in your home folder. And I don't know whether iTerm2 loads it or not.

The `.bashrc` in your home folder should have these lines:
```sh
#export PROMPT_COMMAND="history -a"

shopt -s histappend

CUSTOM_HISTFILE_TIME="~/.command_cache/bash_history_time"; CUSTOM_HISTFILE_DIR="~/.command_cache/bash_history_dir"; CUSTOM_HISTFILE_COMMAND="~/.command_cache/bash_history_command"

PROMPT_COMMAND="history -a; date | xargs echo >>$CUSTOM_HISTFILE_TIME; pwd | xargs echo >>$CUSTOM_HISTFILE_DIR; tail -n 1 $HISTFILE >>$CUSTOM_HISTFILE_COMMAND; $PROMPT_COMMAND"
```
If the above lines are present then the app should work with your default Terminal.app.

As I told you, the app is not written for iTerm2.app(Although it is easy for iTerm2.app to write than for default Terminal.app. So, I might write for it in future).
